title: "AlpacaData"
description: "Blog su AI, Business Intelligence e Analytics"
baseurl: ""
url: "https://alpacadata.github.io"

repository: "alpacadata/alpacadata.github.io"
github_username: "alpacadata"

theme: jekyll-theme-cayman

lang: en
timezone: Europe/Rome
